name: Deploy

on:
  push:
    branches:
      - main
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Build project
        run: bun run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
